name: delivrd_driver
description: Delivrd merchant app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.6+17

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  hive_flutter: ^1.1.0
  hive: ^2.2.1
  get_it: ^7.2.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  firebase_messaging: ^11.1.0
  connectivity: ^3.0.6
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.8
  url_launcher: ^6.1.4
  uuid: ^3.0.6
  image_picker: ^0.8.5+3
  webview_flutter: ^3.0.4
  file_picker: ^5.1.0
  pin_code_fields: ^7.0.0
  permission_handler: ^10.1.0
#  flutter_datetime_picker: ^1.5.1
  fl_chart: ^0.55.2
  file: ^6.1.4
  intl: ^0.18.0
  omni_datetime_picker: ^1.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
